# 1. Basic Tensors

## 1.1 Introduction

In [2]:
import torch as tc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# scaler tensor
scalar = tc.tensor(7)
scalar
print(scalar.item())

7


In [4]:
# vector tensor
vector = tc.tensor([8,8])
vector

tensor([8, 8])

In [5]:
# matrix
MATRIX = tc.tensor([[7,8],[8,7]])
MATRIX

tensor([[7, 8],
        [8, 7]])

In [6]:
# tebnsor
TENSOR = tc.tensor(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    ]
)
print(TENSOR.shape)

torch.Size([2, 3, 4])


## 1.2 Random Tensors

In [7]:
# creating a random tensor

rand_tensor = tc.rand(3, 4,6)
rand_tensor

tensor([[[0.5064, 0.1676, 0.3684, 0.2874, 0.0887, 0.7914],
         [0.2121, 0.7914, 0.8262, 0.8673, 0.2274, 0.2150],
         [0.4112, 0.4392, 0.3767, 0.3821, 0.8364, 0.8515],
         [0.3703, 0.1846, 0.9416, 0.8429, 0.2916, 0.1349]],

        [[0.2547, 0.2499, 0.5164, 0.1120, 0.5221, 0.3316],
         [0.1887, 0.3532, 0.5273, 0.9026, 0.5382, 0.9787],
         [0.9924, 0.6692, 0.0203, 0.3087, 0.4503, 0.6231],
         [0.5174, 0.1268, 0.0646, 0.9718, 0.2073, 0.3889]],

        [[0.3387, 0.9198, 0.3675, 0.7895, 0.3607, 0.5926],
         [0.1481, 0.0478, 0.1760, 0.3187, 0.5980, 0.8914],
         [0.6955, 0.3091, 0.6858, 0.6876, 0.0482, 0.2853],
         [0.3967, 0.5879, 0.6489, 0.0487, 0.3306, 0.8680]]])

In [8]:
# create random tensor with similar shape to an image tensor
random_image_size_tensor = tc.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### 1.2.1 Zero and one tensors

In [9]:
zeros = tc.zeros(size=(3,5))
ones = tc.ones(size=(4,5))
print(zeros,"\n",ones)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### 1.2.2 Range of tensors

In [10]:
range = tc.range(1, 13, 3)
arr = tc.arange(start=1,end=1001,step=77)
print(range,"\n",arr)

C:\Users\TabotCharlesBessong\AppData\Local\Temp\ipykernel_3828\3825928754.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = tc.range(1, 13, 3)


tensor([ 1.,  4.,  7., 10., 13.]) 
 tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])


## 1.3 Tensor datatypes

In [11]:
# float 32 tensors
float_32_tensor = tc.tensor(
    [1, 2, 3, 4], dtype=tc.float16, device=None, requires_grad=False
)
float_32_tensor

tensor([1., 2., 3., 4.], dtype=torch.float16)

## 1.4 Getting information from tensor

In [12]:
# creating a tensor
some_tensor = tc.rand(3,4)

# finding details on the tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.6981, 0.2908, 0.6284, 0.8841],
        [0.4439, 0.3524, 0.0743, 0.1119],
        [0.1703, 0.7071, 0.3619, 0.4250]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of the tensor: cpu


### 1.4.1 Manipulating tensors

In [13]:
# creare a tensor
tensor = tc.tensor([1,2,3])
print(tensor + 12)
print(tensor * 6)
print(tensor / 10)
print(tensor - (-6))

tensor([13, 14, 15])
tensor([ 6, 12, 18])
tensor([0.1000, 0.2000, 0.3000])
tensor([7, 8, 9])


#### 1.4.1.1 Matrix Multiplication

In [14]:
a = tc.tensor([[1,2,3],[4,5,6]])
b = tc.tensor([[1,2],[3,4],[5,6]])
c = tc.matmul(a,b)
print(c)

tensor([[22, 28],
        [49, 64]])


In [15]:
# tensor aggregation
x = tc.arange(0,101,10)
print(tc.min(x),x.argmin())
print(tc.max(x),x.argmax())
print(x.dtype)
print(tc.mean(x.type(tc.float32)))
print(tc.median(x.type(tc.float32)))

tensor(0) tensor(0)
tensor(100) tensor(10)
torch.int64
tensor(50.)
tensor(50.)


## 1.5 Tensor dimension
* Reshaping the tensor
* Viewing the tensor
* Stacking the tensor
* Squeeze The tensor
* Desqueeze The tensor
* Permute The tensor

In [16]:
# create a tensor
x = tc.arange(1,11)
print(x.shape)

torch.Size([10])


### 1.5.1 Reshape, adding another dimension

In [17]:
x_reshaped = x.reshape(5,2)
print(x_reshaped,x_reshaped.shape)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]) torch.Size([5, 2])


In [18]:
y = tc.arange(1,13)
print(y.shape)
y_reshaped = y.reshape(4,3)
print(y_reshaped,y_reshaped.shape)

torch.Size([12])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) torch.Size([4, 3])


### 1.5.2 Stacking of tensors

In [19]:
x_stacked = tc.stack([x,x,x,x])
y_stacked = tc.stack([y,y,y])
print(x_stacked,"\n",y_stacked)
print(x_stacked.shape,"\n",y_stacked.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) 
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([4, 10]) 
 torch.Size([3, 12])


### 1.5.3 Sqeezing tensors

In [20]:
l = tc.zeros(2,1,2,1,2)
print(l,l.size())

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])


In [21]:
m = tc.squeeze(l)
print(m,m.size())

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])


In [22]:
n = tc.squeeze(l,0)
print(n,n.size())

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])


### 1.5.4 Tensor permute
##### Rearrange position of tensors

In [26]:
x1 = tc.rand(2,3,5)
print(x1.size())
print(x1)
print((tc.permute(x1, (2, 0, 1)).size(),"\n",tc.permute(x1, (2, 0, 1)).size()))

torch.Size([2, 3, 5])
tensor([[[0.9489, 0.5121, 0.8088, 0.5577, 0.0087],
         [0.1621, 0.7204, 0.3509, 0.5058, 0.9891],
         [0.5564, 0.0980, 0.9397, 0.9865, 0.0774]],

        [[0.8106, 0.7306, 0.7150, 0.9951, 0.5376],
         [0.0360, 0.6407, 0.1235, 0.2552, 0.7473],
         [0.2539, 0.5894, 0.6426, 0.8122, 0.6197]]])
(torch.Size([5, 2, 3]), '\n', torch.Size([5, 2, 3]))
